services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: SQLserver
    ports:
      - "1433:1433"
    environment: 
      SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - ./data/instnwnd.sql:/docker-entrypoint-initdb.d/instnwnd.sql
  
  airflow:
    image: apache/airflow:2.8.1
    container_name: apache_airflow
    depends_on:
      - sqlserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - "8080:8080"
    command: standalone

volumes:
  sqlserver_data: