services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - ./data/instnwnd.sql:/docker-entrypoint-initdb.d/instnwnd.sql
    networks:
      - etl_net

networks:
  etl_net:
    driver: bridge